/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maininterface;
/**
 *
 * @author admin
 */
public class InterfaceMenu extends javax.swing.JFrame {

    private ViewPatients windowViewPatients = new ViewPatients();
    private ViewRecords windowViewRecords = new ViewRecords();
    
    public InterfaceMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        buttonRefresh = new javax.swing.JButton();
        ViewTab = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPatients = new javax.swing.JMenuItem();
        menuRecords = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        closeTab = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/24x24/add.png"))); // NOI18N
        buttonAdd.setToolTipText("Add");
        buttonAdd.setContentAreaFilled(false);
        buttonAdd.setFocusable(false);
        buttonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonAdd);

        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/24x24/edit.png"))); // NOI18N
        buttonEdit.setToolTipText("Edit");
        buttonEdit.setContentAreaFilled(false);
        buttonEdit.setFocusable(false);
        buttonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonEdit);

        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/24x24/delete.png"))); // NOI18N
        buttonDelete.setToolTipText("Delete");
        buttonDelete.setContentAreaFilled(false);
        buttonDelete.setFocusable(false);
        buttonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonDelete);
        jToolBar1.add(jSeparator3);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setText("Search: ");
        jToolBar1.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jToolBar1.add(jTextField1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/24x24/search.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator2);

        buttonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/24x24/replay.png"))); // NOI18N
        buttonRefresh.setFocusable(false);
        buttonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonRefresh);

        ViewTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        ViewTab.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ViewTabComponentAdded(evt);
            }
        });

        jMenu1.setText("File");

        menuPatients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/16x16/user.png"))); // NOI18N
        menuPatients.setText("Patients");
        menuPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatientsActionPerformed(evt);
            }
        });
        jMenu1.add(menuPatients);

        menuRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/16x16/database.png"))); // NOI18N
        menuRecords.setText("Records");
        menuRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecordsActionPerformed(evt);
            }
        });
        jMenu1.add(menuRecords);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Settings");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/16x16/settings.png"))); // NOI18N
        jMenuItem1.setText("Options");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Close");

        closeTab.setText("Close Tab");
        jMenu2.add(closeTab);
        jMenu2.add(jSeparator1);

        jMenuItem3.setText("Exit");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewTab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewTab, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatientsActionPerformed

        ViewTab.add("Patients",windowViewPatients);
        windowViewPatients.getPatientList(0,"");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPatientsActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed

        windowViewPatients.getPatientList(0, "");
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed

        String stringViewPatients = "maininterface.ViewPatients";
        String stringViewRecords = "maininterface.ViewRecords";
        
        try {
            if(ViewTab.getSelectedComponent().getClass().getName().equals(stringViewPatients)) {
                windowViewPatients.addPatient();
            }
            else if(ViewTab.getSelectedComponent().getClass().getName().equals(stringViewRecords)) {
                windowViewRecords.addRecords();
            }
        }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void menuRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecordsActionPerformed

        ViewTab.add("Records",windowViewRecords);
        windowViewRecords.initiateList(0, "");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRecordsActionPerformed

    private void ViewTabComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ViewTabComponentAdded

        ViewTab.setSelectedIndex(ViewTab.getTabCount()-1);
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTabComponentAdded

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
       
        String stringViewPatients = "maininterface.ViewPatients";
        String stringViewRecords = "maininterface.ViewRecords";
        
        try {
            if(ViewTab.getSelectedComponent().getClass().getName().equals(stringViewPatients)) {
                windowViewPatients.deletePatients();
            }
            else if(ViewTab.getSelectedComponent().getClass().getName().equals(stringViewRecords)) {
                windowViewRecords.deleteRecords();
            }
        }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ViewTab;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JMenuItem closeTab;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuPatients;
    private javax.swing.JMenuItem menuRecords;
    // End of variables declaration//GEN-END:variables
}
