/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maininterface;
import utilities.TableUtilities;

/**
 *
 * @author admin
 */
public class ViewPatients extends javax.swing.JPanel{

    private static final int NUMBER_OF_TABLECOLUMNS = 7;
    private static final String DEFAULT_QUERY = "Select patientID,lastname,firstname,initial,address,contact1,contact2 "
            + "from patientinformation order by lastname";
    
    final static AddPatient windowAddPatient = new AddPatient();
    
    public ViewPatients() {
        initComponents();
    }
    
    public void getPatientList(int rep,String search)
    {
        TableUtilities getTableInformation = new TableUtilities();
        getTableInformation.getList(0, search, tablePatients, NUMBER_OF_TABLECOLUMNS, DEFAULT_QUERY, DEFAULT_QUERY);
    }
    
    public void addPatient()
    {
        windowAddPatient.resetWindow();
        windowAddPatient.setLocationRelativeTo(null);
        windowAddPatient.setTitle("Add Patient - Information");
        windowAddPatient.setResizable(false);
        windowAddPatient.setVisible(true);
    }
    
    public void deletePatients() {
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatients = new javax.swing.JTable();

        tablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LASTNAME", "FIRSTNAME", "INITIAL", "ADDRESS", "CONTACT (1)", "CONTACT (2)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePatients);
        tablePatients.getColumnModel().getColumn(0).setResizable(false);
        tablePatients.getColumnModel().getColumn(0).setPreferredWidth(10);
        tablePatients.getColumnModel().getColumn(1).setResizable(false);
        tablePatients.getColumnModel().getColumn(1).setPreferredWidth(200);
        tablePatients.getColumnModel().getColumn(3).setResizable(false);
        tablePatients.getColumnModel().getColumn(3).setPreferredWidth(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePatients;
    // End of variables declaration//GEN-END:variables
}
